name: upload

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: python3 -m pip install --user --upgrade poetry
      - name: build
        run: poetry build
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
